version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: churnapp
      POSTGRES_PASSWORD: churnarwa1234
      POSTGRES_DB: churndb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://churnapp:churnarwa1234@db:5432/churndb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
